### ISSUE TITLE
com.helpscout.beacon.internal.presentation.common.FullScreenImageActivity url() must not be null

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-android-sdk-sample#141]
Hello,
I would like to report a specific device crash.

Beacon SDK: 2.2.1
Device model: Nexus 4
Android OS version: 6.0.1 

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{myappid/com.helpscout.beacon.internal.presentation.common.FullScreenImageActivity}: java.lang.IllegalStateException: url() must not be null
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Actual outcome**
Beacon crash

**Expected outcome**
Beacon should not crash

Thanks,
Binh

**Comment by scottyab** [comment]
Hey @BinhTNT this looks the same issue and device as #142.  The intent extram in this case url that should never be null is for some reason coming up as null which causes this crash. I'm gonna close this and add the details to #142
