### ISSUE TITLE
ClassCastException launching ChatActivity

### ISSUE THREAD

**Issue by GrahamBorland** [helpscout/beacon-android-sdk-sample#160]
**Technical details**

- Beacon version: 2.3.1
- Android OS version: Various (9 and 11, maybe others)
- Device make/model: Various
- Impacted user count: relatively low

**Actual outcome**

We're getting crash reports from several users. This is with version 2.3.1 of the Beacon Android SDK. We've not yet released a build of our app with 2.3.2, but this particular issue was not listed as a fix in the 2.3.2 release notes.

**Expected outcome**

Beacon should not crash.

**Steps to reproduce**

We haven't managed to reproduce locally yet.

**Screenshots/Screen Recording**

Breadcrumbs of user activity leading up to the crash:

![image](https://user-images.githubusercontent.com/5768767/107217166-b476d700-6a05-11eb-87c3-07133e6617d1.png)

**Additional Information**

```
java.lang.ClassCastException: com.helpscout.beacon.internal.presentation.ui.chat.rating.h cannot be cast to com.helpscout.beacon.internal.presentation.ui.chat.header.d
        at com.helpscout.beacon.internal.presentation.ui.chat.header.ChatHeaderView.b(Unknown)
        at com.helpscout.common.mvi.e$a$a.a(Unknown:12)
        at com.helpscout.common.mvi.e$a$a.onChanged(Unknown:2)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at com.helpscout.common.mvi.f$a.a(Unknown:4)
        at com.helpscout.common.mvi.f$a.invoke(Unknown:2)
        at com.helpscout.common.mvi.g.onChanged(Unknown:2)
        at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.lifecycle.Transformations$3.onChanged(Transformations.java:188)
        at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at com.helpscout.common.mvi.MviReducer.a(Unknown:12)
        at com.helpscout.common.mvi.k$a.a(Unknown:5)
        at com.helpscout.common.mvi.MviReducer.b(Unknown:5)
        at com.helpscout.common.mvi.k$a.a(Unknown:7)
        at com.helpscout.common.mvi.k$a.a(Unknown:8)
        at com.helpscout.common.mvi.MviReducer.b(Unknown:5)
        at com.helpscout.common.mvi.MviReducer.a(Unknown:13)
        at com.helpscout.common.mvi.f.a(Unknown:7)
        at com.helpscout.beacon.internal.presentation.ui.chat.header.ChatHeaderView.a(Unknown:9)
        at com.helpscout.beacon.internal.presentation.ui.chat.ChatActivity.onRestoreInstanceState(Unknown:13)
        at android.app.Activity.performRestoreInstanceState(Activity.java:1098)
        at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1339)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3171)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1986)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:215)
        at android.app.ActivityThread.main(ActivityThread.java:6939)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```

**Comment by ScottPetit** [comment]
👋 @GrahamBorland,

Thanks for the report.  Fortunately, although it wasn't spelled out in our release notes, we believe this was fixed in `2.3.2`.  So our recommendation would be to upgrade to`2.3.2`.  If you do start seeing crash reports from `2.3.2` please feel free to reopen.
