### ISSUE TITLE
Insta-crash when compiled using Android Studio 4.2.0 and Kotlin 1.5.0

### ISSUE THREAD

**Issue by iamstuffed** [helpscout/beacon-android-sdk-sample#170]
When attempting to launch BeaconActivity, I get the following error: 
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: co.fable.fable.internal, PID: 2439
    java.lang.NoSuchMethodError: No virtual method elapsedNow-UwyO8pc()D in class Lkotlin/time/TimeMark; or its super classes (declaration of 'kotlin.time.TimeMark' appears in /data/app/~~iB8iLsXwdUnKy_i1xZQoLg==/co.fable.fable.internal-8ec0UMUUDQkCWuJlY-596g==/base.apk!classes15.dex)
        at org.koin.core.time.MeasureKt.measureDuration(Measure.kt:63)
        at org.koin.core.KoinApplication.modules(KoinApplication.kt:63)
        at com.helpscout.beacon.a.d.a.c$a$a.a(Unknown Source:17)
        at com.helpscout.beacon.a.d.a.c$a$a.invoke(Unknown Source:2)
        at org.koin.dsl.KoinApplicationKt.koinApplication(KoinApplication.kt:28)
        at com.helpscout.beacon.a.d.a.c$a.a(Unknown Source:22)
        at com.helpscout.beacon.a.d.a.c$a.a(Unknown Source:6)
        at com.helpscout.beacon.internal.presentation.common.c.r(Unknown Source:13)
        at com.helpscout.beacon.internal.presentation.common.c.onCreate(Unknown Source:3)
        at com.helpscout.beacon.internal.presentation.ui.home.HomeActivity.onCreate(Unknown Source:0)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

I am using version 3.0.1 from Maven Central.

This is similar to these issues:
https://github.com/helpscout/beacon-android-sdk-sample/issues/124
https://github.com/InsertKoinIO/koin/issues/847

**Comment by sipersso** [comment]
Same here

**Comment by sipersso** [comment]
I really think you should disable loggin for Koin as mentioned here https://github.com/InsertKoinIO/koin/issues/1076#issuecomment-829037282

Right now, this crashes my app in production every time someone tries to reach out for help. :/

**Comment by guillaume-tgl** [comment]
I had the same issue when I upgraded to Kotlin 1.5.0 and was able to get rid of the issue by downgrading to 1.4.10.

**Comment by sipersso** [comment]
@guillaume-tgl yes, I did that too. For the folks at HelpScout.... and email about an issue like this would have been nice. I discovered it through the crash reporting tool in production :/

**Comment by scottyab** [comment]
Thanks for the report we were not aware of this crash/incompatibility with Koltin 1.5.0. Also thanks for the pointers to the Koin logger level downgrade that could very well be an ideal short term solution until Koin has something official. I'll get an internal issue raised for this. In the meantime (as people have mentioned in this thread) recommend downgrading to Koltin `1.4.x`

**Comment by sipersso** [comment]
Looks like Koin is working on it https://github.com/Sage-Bionetworks/AssessmentModel-KotlinNative/pull/81.

**Comment by jotaemepereira** [comment]
Thanks for the info @sipersso. We are working in as solution, we will let you know when it's ready.

**Comment by scottyab** [comment]
Hi @iamstuffed @sipersso @guillaume-tgl We've just pushed a minor update version [3.0.2](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md#version-302-2020-05-18) to address this crashing issue caused by Koin. Thanks for raising this! Please do let us know if this doesn't resolve the crashing issue you were experiencing.
