### ISSUE TITLE
Koin 3.1.0 incompatible with Beacon 3.0.2 causes crash on Beacon launch

### ISSUE THREAD

**Issue by hrules6872** [helpscout/beacon-android-sdk-sample#173]
Recent Koin release (3.1.0) has breaking changes, so Beacon SDK crashes at startup.

**Comment by scottyab** [comment]
Hey @hrules6872, Just so I'm clear, you're using the latest version of Koin 3.1.0 and this is incompatible with Beacon 3.0.2? 

Can you provide more details on the crash (i.e stack trace) you are seeing? Also which version of Kotlin are you using?

**Comment by hrules6872** [comment]
That's it.

Kotlin 1.5.10 + Koin 3.1.0 + Beacon SDK 3.0.2

`java.lang.NoSuchMethodError: No virtual method makeOptions(ZZ)Lorg/koin/core/definition/Options; in class Lorg/koin/core/module/Module; or its super classes (declaration of 'org.koin.core.module.Module' appears in ...)
        at com.helpscout.beacon.internal.presentation.inject.modules.AppModuleKt$appModule$1.invoke(Unknown Source:10)
        at com.helpscout.beacon.internal.presentation.inject.modules.AppModuleKt$appModule$1.invoke(Unknown Source:2)
        at org.koin.dsl.ModuleKt.module(Module.kt:31)
        at org.koin.dsl.ModuleKt.module$default(Module.kt:29)
        at com.helpscout.beacon.internal.presentation.inject.modules.AppModuleKt.<clinit>(Unknown Source:6)
        at com.helpscout.beacon.internal.presentation.inject.modules.AppModuleKt.getAppModule(Unknown Source:0)
        at com.helpscout.beacon.a.d.a.c$a.<clinit>(Unknown Source:18)
        at com.helpscout.beacon.a.d.a.c.<clinit>(Unknown Source:0)
        at com.helpscout.beacon.internal.presentation.common.c.q(Unknown Source:0)
        at com.helpscout.beacon.internal.presentation.common.c.onCreate(Unknown Source:3)
        at com.helpscout.beacon.internal.presentation.ui.home.HomeActivity.onCreate(Unknown Source:0)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`


Koin 3.0.1 (which Beacon SDK uses): https://github.com/InsertKoinIO/koin/blob/3.0.1/core/koin-core/src/commonMain/kotlin/org/koin/core/definition/Options.kt

Koin 3.1.0 (that class is no longer there): https://github.com/InsertKoinIO/koin/tree/master/core/koin-core/src/commonMain/kotlin/org/koin/core/definition

**Comment by scottyab** [comment]
Hey @hrules6872, Just to confirm I have recreated the crash you are seeing due to this breaking change from Koin `3.1.0`. I have created an internal [issue](https://helpscout.atlassian.net/browse/ANDSDK-673) for this. 

In the meantime to resolve this crash is it possible for you to revert to an earlier version of Koin i.e `3.0.2`.

**Comment by hrules6872** [comment]
any ETA on this?

**Comment by jotaemepereira** [comment]
Hey @hrules6872 we do not have an estimate yet. Did you try reverting `Koin` to an earlier version? We will let you know when this is resolved.

**Comment by krobert** [comment]
Hey @jotaemepereira any updates on this ? Can't be a big change. Im struggling with this issue too, i need that koin update...

**Comment by jotaemepereira** [comment]
@krobert Hey @krobert. We are currently working in the next release, and includes a fix for this issue, we will let you know when it is ready.

**Comment by krobert** [comment]
@jotaemepereira any updates? its been a while, i will also report another issue with the current version in a few minutes

**Comment by jotaemepereira** [comment]
Hey @krobert, we don't have an update on this issue at this time. We'll update you here on this thread when it gets resolved.

**Comment by scottyab** [comment]
Thanks again for flagging this @hrules6872, @DannyThompson and @krobert Beacon Android SDK version [4.0.0](https://github.com/helpscout/beacon-android-sdk-sample/blob/main/CHANGELOG.md#version-400-2021-01-17) bumps the version of Java, Kotlin and Koin to resolve this issue. Please let us know if you experience any issues - please note the breaking changes that have been introduced partly to do with the update to target API 31 and AGP 7.x.x.
