### ISSUE TITLE
NullPointerException thrown when viewing list of previous conversations... (specific conversation causing crash)

### ISSUE THREAD

**Issue by davidhole** [helpscout/beacon-android-sdk-sample#20]
* Beacon version: 0.2.5
* Android OS version: 8.1 (occurring on all version)
* Device make/model: OnePlus/5T (occurring on all devices)

**Steps to reproduce**
1. Call BeaconActivity.open(context);
2. Scroll down list of 'Previous messages'

**Actual outcome**
A NullPointerException is thrown. Beacon should should check for a null reference prior to calling getCreatedBy() on the BeaconConversationThreadPreview thread.

It's possible that this is related to data specific to my logged in Beacon user, however this be handled gracefully and not cause an error like this to be thrown...

** STACK TRACE **
2018-10-26 14:03:26.510 23403-23403/com.ovatu.manager E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ovatu.manager, PID: 23403
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.helpscout.beacon.internal.model.BeaconPreviousMessageCreatedBy com.helpscout.beacon.internal.model.BeaconConversationThreadPreview.getCreatedBy()' on a null object reference
        at com.helpscout.beacon.internal.domain.conversations.b$a.e(Unknown Source:4)
        at com.helpscout.beacon.internal.domain.conversations.b$a.a(Unknown Source:22)
        at com.helpscout.beacon.internal.domain.conversations.b$a.a(Unknown Source:2)
        at com.helpscout.beacon.internal.common.a.a.onBindViewHolder(Unknown Source:23)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
        at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
        at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
        at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
        at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
        at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2018-10-26 14:03:26.583 1897-4852/system_process W/ActivityManager:   Force finishing activity com.ovatu.manager/com.helpscout.beacon.internal.domain.conversations.BeaconConversationsActivity

**Comment by scottyab** [comment]
Hey @davidhole thanks for raising this and agree we should handle this better. I've added to the top of our bug fixing queue.

**Comment by davidhole** [comment]
Thanks @scottyab, great news :)

**Comment by scottyab** [comment]
Hey @davidhole This fix was included in v0.2.6 released yesterday - Thanks to @jotaemepereira for the fix!
