### ISSUE TITLE
Dependency Issue with kotlin-coroutines-android

### ISSUE THREAD

**Issue by klinker24** [helpscout/beacon-android-sdk-sample#23]
I did find a solution to this problem on my own. I am just opening this issue for visibility, so that others could see it as well, in case they run into the same thing. There is also a potential fix at the bottom, but I don't know the consequences of it.

* Beacon version: 0.2.6
* Android OS version: 9.0.0
* Device make/model: Google Pixel 3 XL

**Steps to reproduce**

1. Initialize the library using the steps in the readme (added the dependencies and initialized it with the beacon ID).
2. Try to open the `BeaconActivity` using `BeaconActivity.open`.

**Actual outcome**

The `BeaconActivity` did not start and resulted in the following stack trace: 

```
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/experimental/android/HandlerContextKt;
        at com.helpscout.beacon.internal.domain.config.a.<init>(Unknown Source:4)
        at com.helpscout.beacon.internal.domain.a.d(Unknown Source:14)
        at com.helpscout.beacon.internal.domain.a.create(Unknown Source:106)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:135)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:103)
        at com.helpscout.beacon.internal.domain.config.BeaconConfigActivity$f.a(Unknown Source:27)
        at com.helpscout.beacon.internal.domain.config.BeaconConfigActivity$f.invoke(Unknown Source:0)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.helpscout.beacon.internal.domain.config.BeaconConfigActivity.c(Unknown Source:7)
        at com.helpscout.beacon.internal.domain.config.BeaconConfigActivity.onCreate(Unknown Source:11)
        at android.app.Activity.performCreate(Activity.java:7174)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.coroutines.experimental.android.HandlerContextKt" on path: DexPathList
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.helpscout.beacon.internal.domain.config.a.<init>(Unknown Source:4) 
        at com.helpscout.beacon.internal.domain.a.d(Unknown Source:14) 
        at com.helpscout.beacon.internal.domain.a.create(Unknown Source:106) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:135) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:103) 
        at com.helpscout.beacon.internal.domain.config.BeaconConfigActivity$f.a(Unknown Source:27) 
        at com.helpscout.beacon.internal.domain.config.BeaconConfigActivity$f.invoke(Unknown Source:0) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at com.helpscout.beacon.internal.domain.config.BeaconConfigActivity.c(Unknown Source:7) 
        at com.helpscout.beacon.internal.domain.config.BeaconConfigActivity.onCreate(Unknown Source:11) 
        at android.app.Activity.performCreate(Activity.java:7174) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Expected outcome**

The `BeaconActivity` should start and provide me with the list of help topics and to get in touch.

**Notes on the issue**

I think it is pretty clear that something is wrong with the dependencies here, but I couldn't figure out what the issue is. I had verified that the sample in this repo does build and runs correctly, so I knew it was an issue on my side. 

Some info on my project:

* Min SDK: 21
* Compile SDK: 28
* Target SDK: 28
* I am using Kotlin 1.3.10 within the app and had not previously (explicitly) included the `org.jetbrains.kotlinx:kotlinx-coroutines-android` dependency. 

What I have tried: 

* I matched all of the gradle and gradle plugin versions with the sample. It still didn't work
* I tried kotlin `1.2.71` (which is defined in the sample) and kotlin `1.3.10` (which is the latest)
* I added the `org.jetbrains.kotlinx:kotlinx-coroutines-android` dependency to my own project, which still didn't work. I tried the `1.0.1` (current) and `0.20` (which is defined in the sample project)

I also found this, which finally pointed me to the issue: https://github.com/Kotlin/kotlinx.coroutines/issues/255

With this change, it changed the file output name for the compiled `HandlerContext.kt` file from `HandlerContextKt` -> `HandlerContext`. This change would have been in the `1.0.1` version of the `kotlinx-coroutines-android` file.

So, the issue is that I had another dependency in my project that was requesting `org.jetbrains.kotlinx:kotlinx-coroutines-android:1.0.1`. By doing so, it was clobbering the `kotlinx-coroutines-android` dependency that should have been imported with these libraries. Along with the name change, that was what was causing the crash.

**Workaround for `v0.2.6` of the beacon libraries**

Force the resolution of the `kotlinx-coroutines-android` dependency to `v0.2.6`. In the root `build.gradle` file:

```groovy
allprojects {

    configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            def requested = details.requested
            if (requested.group == 'org.jetbrains.kotlinx' && requested.name == 'kotlinx-coroutines-android') {
                details.useVersion '0.20'
            }
        }
    }

}
```

**Possible solution**

I think that just updating to the latest version of Kotlin and the `kotlinx-coroutines-android` library will solve this issue, in the future. 

For me, the conflicting dependency was `WorkManager`. By using the Java version of the work manager runtime, instead of the kotlin version, this library worked just fine. 

```groovy
// java
implementation "android.arch.work:work-runtime:$work_version"
// kotlin
implementation "android.arch.work:work-runtime-ktx:$work_version"
```

**Comment by scottyab** [comment]
Hi @klinker24, thanks for flagging this and writing up the solution 👏 . We have plans to move to Kotlin 1.3 soon.

**Comment by scottyab** [comment]
Hey @klinker24 closing this issue as in v0.2.8 we've migrated to Kotlin 1.3. Thanks again for the write-up and solution that others could use 💯
