### ISSUE TITLE
Android X Integration

### ISSUE THREAD

**Issue by klinker24** [helpscout/beacon-android-sdk-sample#25]
* Beacon version: 0.2.6
* Android OS version: 9.0.0
* Device make/model: Pixel 3

**Steps to reproduce**
1. Include the library in a project that has been migrated to Android X
2. Open the "Get in touch" link within the `BeaconActivity`, to start a new conversation

If you open the sample project in Android Studio 3.2 and above, you can easily reproduce this issue by using the "Migrate to Android X" feature within Android Studio. That is where following log came from.

To migrate to Android X, you need to be on the latest version of the Gradle plugin. I have updated your `dependencies.gradle` file for this:

```gradle
ext {

    // Sdk and tools
    minSdkVersion = 21
    targetSdkVersion = 28
    compileSdkVersion = 28
    dexcountVersion = '0.8.2'

    coroutinesVersion = '1.0.1'
    gradlePluginVersion = '3.2.1'
    kotlinVersion = '1.3.10'

    // Testing
    jUnitVersion = '4.12'
    mockitoVersion = '1.10.19'
    assertJ = '1.7.1'

    // Android libraries
    supportLibrary = '28.0.0'
    constraintLayoutVersion = '1.0.2'

    // Beacon
    beaconCoreVersion = '0.2.6'
    beaconUiVersion = '0.2.6'

}
```

**Actual outcome**

It results in the following crash:

```
2018-11-20 09:37:00.156 13805-13805/net.helpscout.samples.beacon.kotlin E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.helpscout.samples.beacon.kotlin, PID: 13805
    java.lang.RuntimeException: Unable to start activity ComponentInfo{net.helpscout.samples.beacon.kotlin/com.helpscout.beacon.internal.domain.send.BeaconSendMessageActivity}: android.view.InflateException: Binary XML file line #17: Could not inflate Behavior subclass com.helpscout.beacon.internal.common.widget.DisableableAppBarLayoutBehavior
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2914)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.view.InflateException: Binary XML file line #17: Could not inflate Behavior subclass com.helpscout.beacon.internal.common.widget.DisableableAppBarLayoutBehavior
     Caused by: java.lang.RuntimeException: Could not inflate Behavior subclass com.helpscout.beacon.internal.common.widget.DisableableAppBarLayoutBehavior
        at androidx.coordinatorlayout.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:622)
        at androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2805)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1704)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:111)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.helpscout.beacon.internal.domain.send.BeaconSendMessageActivity.onCreate(Unknown Source:5)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
2018-11-20 09:37:00.156 13805-13805/net.helpscout.samples.beacon.kotlin E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:620)
        	... 28 more
     Caused by: java.lang.NoSuchMethodError: No virtual method setDragCallback(Lcom/google/android/material/appbar/AppBarLayout$Behavior$DragCallback;)V in class Lcom/helpscout/beacon/internal/common/widget/DisableableAppBarLayoutBehavior; or its super classes (declaration of 'com.helpscout.beacon.internal.common.widget.DisableableAppBarLayoutBehavior' appears in /data/app/net.helpscout.samples.beacon.kotlin-qRYJZ6rxD37-HwrxbModMA==/base.apk!classes2.dex)
        at com.helpscout.beacon.internal.common.widget.DisableableAppBarLayoutBehavior.<init>(Unknown Source:18)
        	... 31 more
```

**Expected outcome**

Beacon should not crash when used in a project that has been migrated to Android X.

**Notes**

For a project migrated to Android X, the Android Gradle plugin will automatically convert any dependencies to use the Android X counterpart. They call it [Jetify](https://developer.android.com/jetpack/androidx/). So `AppCompat`, `CoordinatorLayout`, etc will automatically be migrated. That seems to be where the issue lies. Without looking at the code I can't really tell much more. The Gradle plugin must be missing something in this auto-conversion. 

Migrating the library to use Android X would solve this issue, but I do not know what implications that would have on your codebase. There may also be a way for the library to tell Gradle how to do the auto migration, but I have never looked into this. There is probably also a way to refactor the `DisableableAppBarLayoutBehavior` so that the jetifier works correctly.

**Comment by scottyab** [comment]
Hey @klinker24 again epic details in the issue 👏  We are planning to migrate the SDK to Android X as v28 it's the last version of the old style support lib. 

Also we have removed the `DisableableAppBarLayoutBehavior` in next release v0.2.7 that might help this in the near term. Our plan is to update one of the Sample projects to use Android X to ensure we are testing compatibility. I'll leave this open for time being.

**Comment by scottyab** [comment]
Hey @klinker24 closing this issue as PR #29 adds AndroidX support to one of the sample apps to ensure we stay compatible. Thanks!
