### ISSUE TITLE
Crash when opening previous conversation

### ISSUE THREAD

**Issue by jaredandrews** [helpscout/beacon-android-sdk-sample#61]
* Beacon version: 1.0.5

**I have experienced this crash on all devices I have tried which are:**
* Android OS: 9 / Device make/model: Pixel 3
* Android OS: 8.1.0 / Device make/model: LG Aristo 2 Plus
* Android OS: 7 / Device make/model: Samsung Galaxy S7

**Steps to reproduce**
1. Open beacon activity and click "previous conversations"
2. Select a previous conversation from the list

**Actual outcome**
App crashes, with this stacktrace:

```2019-08-26 16:08:19.254 17862-17862/com.example.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.app, PID: 17862
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/text/HtmlCompat;
        at com.helpscout.beacon.internal.extensions.ViewExtensionsKt.formatTextAsHtmlWithImages(Unknown Source:68)
        at com.helpscout.beacon.internal.domain.conversation.z$a.b(Unknown Source:27)
        at com.helpscout.beacon.internal.domain.conversation.z$a.a(Unknown Source:61)
        at com.helpscout.beacon.internal.domain.conversation.z$a.a(Unknown Source:2)
        at com.helpscout.beacon.internal.common.a.a.onBindViewHolder(Unknown Source:23)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:19728)
        at android.view.ViewGroup.layout(ViewGroup.java:6149)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19728)
        at android.view.ViewGroup.layout(ViewGroup.java:6149)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19728)
        at android.view.ViewGroup.layout(ViewGroup.java:6149)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19728)
        at android.view.ViewGroup.layout(ViewGroup.java:6149)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19728)
        at android.view.ViewGroup.layout(ViewGroup.java:6149)
        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:606)
        at android.view.View.layout(View.java:19728)
        at android.view.ViewGroup.layout(ViewGroup.java:6149)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19728)
        at android.view.ViewGroup.layout(ViewGroup.java:6149)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19728)
        at android.view.ViewGroup.layout(ViewGroup.java:6149)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19728)
        at android.view.ViewGroup.layout(ViewGroup.java:6149)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
2019-08-26 16:08:19.260 17862-17862/com.example.app E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19728)
        at android.view.ViewGroup.layout(ViewGroup.java:6149)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:819)
        at android.view.View.layout(View.java:19728)
        at android.view.ViewGroup.layout(ViewGroup.java:6149)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2615)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2324)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1469)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7315)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:988)
        at android.view.Choreographer.doCallbacks(Choreographer.java:800)
        at android.view.Choreographer.doFrame(Choreographer.java:735)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:974)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:175)
        at android.app.ActivityThread.main(ActivityThread.java:6724)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.text.HtmlCompat" on path: DexPathList[[zip file "/data/app/com.example.app-rceyVBZv-k1kKKEuz7lnww==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.app-rceyVBZv-k1kKKEuz7lnww==/lib/arm, /data/app/com.example.app-rceyVBZv-k1kKKEuz7lnww==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
            ... 78 more
```

I am integrating Beacon into my app which targets SDK 27. I tried this using the sample project and did not experience this crash. Must be a configuration issue on my end but I'm not sure where to look any help would be appreciated.

My app did not have support-v4 in it's dependencies, I tried adding it to no effect.

Thank you!

**Expected outcome**
Previous conversation should open

**Screenshots or GIFs**
Any examples of the issue

**Comment by scottyab** [comment]
Moved into a private convo, but leaving this issue open until we've resolved.

**Comment by scottyab** [comment]
Resolved by updating the host app's appcompat and design libs to 28.0.0. Thanks for raising the issue @jaredandrews.
