### ISSUE TITLE
R8 build issue caused by Incompatibility with firebase perf monitoring 19.0.0   

### ISSUE THREAD

**Issue by tir38** [helpscout/beacon-android-sdk-sample#62]
* Beacon version:  1.0.5
* Android OS version: 23 - 28
* Device make/model: many

**Steps to reproduce**
1. launch BeaconActivity (see source below)
2. app crashes

**Actual outcome**

```
2019-09-03 11:16:08.982 26093-26093/com.example.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.debug, PID: 26093
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/helpscout/beacon/internal/common/d;
        at com.helpscout.beacon.ui.BeaconActivity.open(Unknown Source:0)
        at com.example.feedback.DefaultFeedbackRepo.showFeedbackView(DefaultFeedbackRepo.java:121)
        at com.example.helpsheet.HelpSheetPresenter.onFeedbackClicked(HelpSheetPresenter.java:51)
        at com.example.helpsheet.HelpSheetView.lambda$onFinishInflate$1$HelpSheetView(HelpSheetView.java:34)
        at com.example.helpsheet.-$$Lambda$HelpSheetView$im3v--W6XS2fKJKLsPUgfXiejlY.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: com.helpscout.beacon.internal.common.d
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.helpscout.beacon.ui.BeaconActivity.open(Unknown Source:0) 
        at com.example.feedback.DefaultFeedbackRepo.showFeedbackView(DefaultFeedbackRepo.java:121) 
        at com.example.helpsheet.HelpSheetPresenter.onFeedbackClicked(HelpSheetPresenter.java:51) 
        at com.example.helpsheet.HelpSheetView.lambda$onFinishInflate$1$HelpSheetView(HelpSheetView.java:34) 
        at com.example.helpsheet.-$$Lambda$HelpSheetView$im3v--W6XS2fKJKLsPUgfXiejlY.onClick(Unknown Source:2) 
        at android.view.View.performClick(View.java:6597) 
        at android.view.View.performClickInternal(View.java:6574) 
        at android.view.View.access$3100(View.java:778) 
        at android.view.View$PerformClick.run(View.java:25885) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/helpscout/beacon/internal/store/I;
        at com.helpscout.beacon.ui.BeaconActivity.open(Unknown Source:0) 
        at com.example.feedback.DefaultFeedbackRepo.showFeedbackView(DefaultFeedbackRepo.java:121) 
        at com.example.helpsheet.HelpSheetPresenter.onFeedbackClicked(HelpSheetPresenter.java:51) 
        at com.example.helpsheet.HelpSheetView.lambda$onFinishInflate$1$HelpSheetView(HelpSheetView.java:34) 
        at com.example.helpsheet.-$$Lambda$HelpSheetView$im3v--W6XS2fKJKLsPUgfXiejlY.onClick(Unknown Source:2) 
```

**Expected outcome**
Beacon should have navigated to BeaconActivity

**Source where we nav to BeaconActivity**

```
import androidx.annotation.NonNull;

import com.helpscout.beacon.Beacon;
import com.helpscout.beacon.internal.core.model.BeaconContactForm;
import com.helpscout.beacon.model.BeaconConfigOverrides;
import com.helpscout.beacon.model.BeaconScreens;
import com.helpscout.beacon.model.PreFilledForm;
import com.helpscout.beacon.ui.BeaconActivity;
import com.newrelic.agent.android.R;
import com.example.User;
import com.example.util.Strings;

import java.util.ArrayList;
import java.util.HashMap;

class Scratch {
    private static final String BEACON_ID = "xxxxx";
    private static final String ATTRIBUTE_KEY_USER_ID = "User ID";

    private User currentUser;

    public void main() {
        new Beacon.Builder()
                .withBeaconId(BEACON_ID)
                .withLogsEnabled(true)
                .build();

        String currentEmail = Strings.EMPTY;
        if (currentUser == null || currentUser.getEmails().isEmpty()) {
            // If user has no email, then they can provide one themselves each time they send
            // feedback, so logout just in case they change emails; don't want them to accidentally
            // send feedback with the previous email.
            Beacon.logout();
        } else {
            // Can only log in manually if the user has an email to provide upon opening the activity.
            // If they don't we can't log them in automatically.
            currentEmail = currentUser.getEmails().get(0).getBody();
            Beacon.login(currentEmail);
        }

        // Initialize the "Contact Form" which has a Subject Line, a Logs field, and a message
        // field. TODO: re-enable custom fields when we can hide them for logs.
        BeaconContactForm contactForm = new BeaconContactForm(false, true,
                true, false, false);

        if (currentUser != null) {
            setAttributes(currentUser);
        }

        // Configure with the contact form and our desired color.
        // The color expects a Hex String, hence converting to HexString.
        Beacon.setConfigOverrides(new BeaconConfigOverrides(false, true, false, contactForm,
                "#" + Integer.toHexString(context.getResources().getColor(R.color.primary))));

        // Pre-fill the form with the user's email (which isn't shown if they already have one pre-populated)
        Beacon.addPreFilledForm(new PreFilledForm(currentEmail, Strings.EMPTY, Strings.EMPTY,
                new HashMap<>(),
                new ArrayList<>()));

        BeaconActivity.open(context, BeaconScreens.CONTACT_FORM_SCREEN, new ArrayList<>());
    }

    // Get the users specific attributes and add them to Beacon
    private void setAttributes(@NonNull final User user) {
        // ...
        Beacon.addAttributeWithKey(ATTRIBUTE_KEY_USER_ID, user.getId());
    }
}
```

At first this looks like a proguard/R8 issue. We thought maybe R8 was stripping some internal Beacon classes. So we updated progurad rules to keep *everything* from `com.helpscout` package (usually overkill) But that still didn't fix the problem.

Upon further investigation I noticed these in our build log

```
> Task :app:transformClassesAndResourcesWithR8ForDebug
R8: Missing class: com.helpscout.beacon.internal.store.I
R8: Missing class: com.helpscout.beacon.internal.store.H
R8: Missing class: com.helpscout.beacon.internal.store.D
R8: Missing class: com.helpscout.beacon.internal.store.C
R8: Missing class: com.helpscout.beacon.internal.store.A
```

The apk still builds fine (no build errors) so I'm not sure these are relevant.

**Comment by scottyab** [comment]
Hi @tir38 thanks for raising, we use Proguard on the SDK, so it'll be obfuscated already but I wonder if there's an incompatibility with R8? Thanks for the sample code I'll see if I can recreate with a R8 version of this Sample app.

**Comment by scottyab** [comment]
Hi @tir38 I've just pushed a [temporary branch](https://github.com/helpscout/beacon-android-sdk-sample/tree/feature/62-r8-issue) with R8 enabled for the Customise Sample app with your sample code added but I'm unable to see the `NoClassDefFoundError` crash or warnings in build. Can you take a look see if it matches your project? if not feel free to submit a PR with changes to that branch so we can have an isolated recreation of the issue you're seeing. Thanks
Thanks

**Comment by tir38** [comment]
@scottyab  I pinpointed the problem on our actual application. The problem happens when we add Firebase Performance Monitoring. If we turn that off then we can launch BeaconActivity just fine. 

I tried to reproduce on your branch and could not get the exact same problem but lots of similar problems all in the ballpark related to conflicting/overlapping Firebase dependencies (I see now that helpscout depends on some Firebase SDKs)

So I first just added firebase perf monitoring https://github.com/tir38/beacon-android-sdk-sample/commit/42f13280a0d400f639649fc02a0f2a1677c9ea07

Building the app `./gradlew clean sample-customisation:installDebug` I then get this build error:

```
Execution failed for task ':sample-customisation:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.google.android.gms.internal.firebase_messaging.zzo found in modules classes.jar (com.google.firebase:firebase-iid:20.0.0) and classes.jar (com.google.firebase:firebase-messaging:17.5.0)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzp found in modules classes.jar (com.google.firebase:firebase-iid:20.0.0) and classes.jar (com.google.firebase:firebase-messaging:17.5.0)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzq found in modules classes.jar (com.google.firebase:firebase-iid:20.0.0) and classes.jar (com.google.firebase:firebase-messaging:17.5.0)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzr found in modules classes.jar (com.google.firebase:firebase-iid:20.0.0) and classes.jar (com.google.firebase:firebase-messaging:17.5.0)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzs found in modules classes.jar (com.google.firebase:firebase-iid:20.0.0) and classes.jar (com.google.firebase:firebase-messaging:17.5.0)
```

I was going to leave it at that but the I wanted to try to directly repro the problem on our app. So I then further turned on R8 and made your sample look like our project https://github.com/tir38/beacon-android-sdk-sample/commit/7f2c506b373828009497336154c1420c286127a7

Trying to build I ended up with a different build error (still unable to repro my original problem):

```
> Task :sample-customisation:transformClassesAndResourcesWithR8ForDebug FAILED
R8: Program type already present: com.google.android.gms.internal.firebase_messaging.zzr

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sample-customisation:transformClassesAndResourcesWithR8ForDebug'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete
```

So for whatever reason including Firebase perf monitoring with Helpscout SDK is causing one or more build/runtime errors.

I'm happy to help debug further LMK.

**Comment by scottyab** [comment]
Hey @tir38 I'm able to resolve the firebase perf issue by forcing newer versions of the firebase dependencies. Using [42f1328](https://github.com/tir38/beacon-android-sdk-sample/commit/42f13280a0d400f639649fc02a0f2a1677c9ea07) as a base I added the following resolution strategies to the build.gradle in the customise sample.  

```
  configurations.all {
        resolutionStrategy.force "com.google.firebase:firebase-core:17.2.0"
        resolutionStrategy.force "com.google.firebase:firebase-iid:20.0.0"
        resolutionStrategy.force "com.google.firebase:firebase-common:19.0.0"
        resolutionStrategy.force "com.google.android.gms:play-services-tasks:17.0.0"
        resolutionStrategy.force "com.google.android.gms:play-services-basement:17.0.0"
        resolutionStrategy.force "com.google.firebase:firebase-messaging:20.0.0"
    }
```

However now I'm seeing the R8 warnings in build and the NoClassDefFoundError crash when attempting to launch the `BeaconActivity`. I'll update my branch and continue to investigate.  

```
 Process: net.helpscout.samples.beacon.customisation, PID: 17528
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/helpscout/beacon/internal/common/d;
        at com.helpscout.beacon.ui.BeaconActivity.a(Unknown Source:0)
        at net.helpscout.sample.beacon.a.a(Unknown Source:158)
        at net.helpscout.sample.beacon.CustomisationActivity.onCreate(Unknown Source:19)
```

**Comment by scottyab** [comment]
Note, we'll update the firebase-messaging to 20.0.0 in a future release so the need for resolution strategy is temporary.

**Comment by scottyab** [comment]
Hey @tir38 I think I have a fix after many hours of tweaking the beacon-ui module's consumer proguard config. As mentioned above I was able to recreate the crash in the [temporary branch](https://github.com/helpscout/beacon-android-sdk-sample/tree/feature/62-r8-issue) and this is now fixed when it points to an internal maven repo with the updated config. I'll see about getting this fix into the next release v1.0.6. Thanks again for reporting. 

Note: You'll still need the above resolution strategies to use the latest firebase-pref.

**Comment by tir38** [comment]
I'll happily guinea pig when ready

**Comment by tir38** [comment]
Tested with latest 1.0.6. Seems to be working great. Thanks!

**Comment by scottyab** [comment]
Great. Thanks for confirming @tir38 :)
