### ISSUE TITLE
App crashes when trying to set PreFilledForm to Beacon

### ISSUE THREAD

**Issue by Ditscheridou** [helpscout/beacon-android-sdk-sample#91]
Thank you for taking the time to submit an issue with all the details shown below. Our engineering team monitors issues submitted and strives to respond with 1-2 business days.

* Beacon version: 2.1.0
* Android OS version: 9.0
* Device make/model: Xiami A3

**Steps to reproduce**
1. Add the SDK to the project, initialize the beacon 
2. Follow the tutorial for adding PreFilledForms
3. write Beacon.addPreFilledForm(PreFilledForm())

**Actual outcome**
App crashes with this error: 

`    java.lang.IllegalArgumentException: Cannot serialize Kotlin type com.helpscout.beacon.model.PreFilledForm. Reflective serialization of Kotlin classes without using kotlin-reflect has undefined and unexpected behavior. Please use KotlinJsonAdapter from the moshi-kotlin artifact or use code gen from the moshi-kotlin-codegen artifact.
        at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:83)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:98)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:72)
        at com.helpscout.beacon.internal.core.data.BeaconPreferences.setPreFilledForm(BeaconPreferences.kt:255)
        at com.helpscout.beacon.Beacon.addPreFilledForm(Beacon.java:283)
        at com.vmaxpro.view.fragments.settings.SettingsFragment$setupReportErrorButton$1.onClick(SettingsFragment.kt:72)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25889)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6746)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Expected outcome**
Beacon should open the activity with the prefilled form

**Screenshots or GIFs**
Any examples of the issue

**Comment by Ditscheridou** [comment]
So basically, i am using a FloatingActionButton with this code: 

`binding.buttonReportError.setOnClickListener {
            Beacon.addPreFilledForm(PreFilledForm(subject = "Bug report for version ${BuildConfig.VERSION_NAME}", email = useremail))
            BeaconActivity.open(requireContext());
        }`

The initialization is done in my Application class in the oncreate method as following: 
`Beacon.Builder()
                .withBeaconId("My Beacon id")
                .withLogsEnabled(true)
                .withContext(applicationContext)
                .build()`

**Comment by adrianne-helpscout** [comment]
👋 @Ditscheridou The first thing that stands out to me about the code that you have provided above is your beacon ID. You are currently using: "My Beacon id". It should look something like this: 75d21b99-41g4-4d54-9z8c-08679b4759e3

[Here's a screenshot](https://c.hlp.sc/L1u7pgAG) of the beacon settings installation section where you will find this ID number.

If you are having trouble locating this information, please contact us at support@helpscout.com and our customer's team can look the appropriate information up for you.

**Comment by Ditscheridou** [comment]
i know, but i will not show my beacon id in a public github ticket? so thats why i wrote this placeholder there

**Comment by adrianne-helpscout** [comment]
@Ditscheridou Thanks for confirming that you were using your Beacon ID and not the stock text.

**Comment by aliripe** [comment]
@Ditscheridou We've been able to reproduce this internally and we have created a ticket to track it. We will let you know once we have a fix for it.

Ticket: [ANDSDK-402](https://helpscout.atlassian.net/browse/ANDSDK-402)

**Comment by scottyab** [comment]
Hi @Ditscheridou this issue has been resolved in release 2.1.1 - Please do reopen if you're still experiencing the issue.

**Comment by scottyab** [comment]
Hi @DishaMungra We discovered a regression issue when upgrading from Beacon SDK below version 2.0.2 directly to 2.1.1. Therefore removed 2.1.1 and aim to resolve this issue in the next release. We'll update you once this is released, thank you for your patience.

**Comment by scottyab** [comment]
Hi @Ditscheridou with today's release of 2.1.2 #112 this issue should be now resolved. Thanks for the patience.
